<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>EduVibe</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	  <UserSecretsId>a3963708-6214-4ac9-92d7-77e16db6cc42</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<None Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.12" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.12" />
		<PackageReference Include="SendGrid" Version="9.29.3" />
		<PackageReference Include="SendGrid.Extensions.DependencyInjection" Version="1.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BLL\BLL.csproj" />
	</ItemGroup>

</Project>
